Repository torn-exchange/web, pull requests merged in 2024-11, with the labels that each got.

#43 Fix website slowness
  main/te_utils.py
  main/templates/main/price_list.html
  main/templates/main/price_list_creation.html
  main/templatetags/custom_tags.py
  main/urls.py
  main/views.py
  torntrades/settings.py
Labels: bug

#45 Fixed update items script with APIv2 support
  main/management/commands/delete_old_keys.py
  main/management/commands/recover_api_keys.py
  main/management/commands/update_items2.py
  main/management/commands/update_properties.py
  main/te_utils.py
Labels: bug, enhancement

#46 Pricelist search
  main/management/commands/update_items2.py
  main/models.py
  main/templates/main/price_list.html
Labels: enhancement

#47 (feature) new page to search custom services
  main/filters.py
  main/te_utils.py
  main/templates/main/includes/navbar.html
  main/templates/main/search_services.html
  main/urls.py
  main/views.py
Labels: feature

#48 Fix update script so that it repeats failed requests
  main/management/commands/delete_old_keys.py
  main/management/commands/update_items2.py
Labels: bug

#49 Improve services page and home page
  main/filters.py
  main/management/commands/update_items2.py
  main/te_utils.py
  main/templates/main/home.html
  main/templates/main/includes/changelog.html
  main/templates/main/includes/leaderboard.html
  main/templates/main/includes/most_receipts.html
  main/templates/main/includes/navbar.html
  main/templates/main/includes/top_active_traders.html
  main/templates/main/search_services.html
  main/views.py
  users/templates/users/login.html
  users/views.py
Labels: feature

#50 Museum Helper page; added new services
  main/management/commands/services_update.py
  main/migrations/0038_auto_20241114_0015.py
  main/models.py
  main/te_utils.py
  main/templates/main/includes/navbar.html
  main/templates/main/museum_helper.html
  main/templates/main/price_list_creation.html
  main/urls.py
  main/views.py
Labels: feature

#53 Minor changes
  README.md
  requirements.txt
  torntrades/README.md
Labels: documentation

#59 Improve calculator page
  main/static/main/css/bootstrap4-daydream.css
  main/te_utils.py
  main/templates/main/about.html
  main/templates/main/calculator.html
  main/templates/main/home.html
  main/templates/main/includes/footer.html
  main/templates/main/listings.html
  main/templates/main/search_services.html
  main/templates/main/services_list.html
  main/views.py
Labels: feature
