Repository torn-exchange/web, pull requests merged in 2024-12, with the labels that each got.

#73 fix voting on services page
  main/templates/main/includes/navbar.html
  main/templates/main/services_list.html
Labels: bug

#55 add subpages for analytics; improve several things
  main/profile_stats.py
  main/templates/main/all_receipts.html
  main/templates/main/all_sellers.html
  main/templates/main/analytics.html
  main/templates/main/includes/dashboard_cards/latest_trades.html
  main/templates/main/includes/dashboard_cards/main_statistics.html
  main/templates/main/includes/dashboard_cards/receipt_history.html
  main/templates/main/includes/dashboard_cards/top_sellers.html
  main/templates/main/includes/pagination.html
  main/templates/main/listings.html
  main/templates/main/price_list.html
  main/templates/main/search_services.html
  main/templatetags/custom_tags.py
  main/urls.py
  main/views.py
Labels: feature

#74 introduce Sentry logging
  main/templates/main/base.html
  requirements.txt
  torntrades/settings.py
Labels: feature

#75 Introduce file-based caching
  README.md
  main/views.py
  requirements.txt
  torntrades/settings.py
Labels: feature

#76 Security fixes
  main/views.py
  requirements.txt
  users/views.py
Labels: dependencies
