Repository torn-exchange/web, pull requests merged in 2025-03, with the labels that each got.

#112 Theme dark/light enhancements
  main/static/main/css/te.css
  main/static/main/css/test.css
  main/static/main/images/logocentral.png
  main/static/main/images/mainlogo.png
  main/templates/main/analytics.html
  main/templates/main/base.html
  main/templates/main/calculator.html
  main/templates/main/edit_services.html
  main/templates/main/employee_listings.html
  main/templates/main/home.html
  main/templates/main/includes/changelog.html
  main/templates/main/includes/leaderboard.html
  main/templates/main/includes/most_receipts.html
  main/templates/main/includes/navbar.html
  main/templates/main/includes/profile_card.html
  main/templates/main/listings.html
  main/templates/main/losses_listings.html
  main/templates/main/manage_price_list.html
  main/templates/main/price_list.html
  main/templates/main/price_list_creation.html
  main/templates/main/revives_listings.html
  main/templates/main/search_services.html
  main/templates/main/services_list.html
  main/templates/main/settings.html
  main/templates/main/sitemap.html
  users/forms.py
Labels: UI

#113 hide hidden cats from listings page
  main/management/commands/fix_hidden_cats.py
  main/migrations/0039_listing_hidden.py
  main/models.py
  main/views.py
Labels: bug

#115 Services UI refactor
  main/templates/main/base.html
  main/templates/main/listings.html
  main/templates/main/search_services.html
Labels: feature

#117 Added regex route matching
  main/urls.py
Labels: bug

#120 fix couple url reverses
  main/templates/main/settings.html
  main/urls.py
Labels: bugfix

#118 Fixed System Warnings
  torntrades/settings.py
  users/migrations/0027_profile_hidden_categories.py
  users/migrations/0028_profile_order_categories.py
  users/models.py
Labels: bugfix

#119 Bugfix Ads dropdown menus
  main/static/main/css/te.css
Labels: bugfix

#122 Bugfix/listing links
  main/templates/main/listings.html
Labels: bugfix

#124 Bugfix/urls
  main/urls.py
Labels: bugfix

#125 Fix mobile view for all trades
  main/templates/main/all_receipts.html
Labels: bugfix

#126 Feature/rw listing
  main/filters.py
  main/management/commands/once_create_item_bonuses.py
  main/management/commands/rw_import.py
  main/management/commands/rw_market_import.py
  main/management/commands/update_items2.py
  main/migrations/0040_auto_20250310_2044.py
  main/migrations/0041_alter_itemvariation_price.py
  main/migrations/0042_alter_itemvariation_owner.py
  main/migrations/0043_auto_20250311_2121.py
  main/migrations/0044_itemvariationbonuses_description.py
  main/models.py
  main/services/__init__.py
  main/services/api/torn/items/torn_item_market_api_service.py
  main/services/api/torn/player/torn_player_api_service.py
  main/services/api/torn/torn_api_error_handler.py
  main/services/api/torn/torn_api_service.py
  main/static/main/css/te.css
  main/templates/main/includes/navbar.html
  main/templates/main/includes/pagination.html
  main/templates/main/rw_listings.html
  main/urls.py
  main/views.py
  users/migrations/0030_auto_20250310_0917.py
  users/migrations/0031_alter_profile_api_key.py
  users/models.py
  users/views.py
Labels: feature

#139 Added tooltips
  main/templates/main/rw_listings.html
Labels: feature

#138 RW Listing - Ordering bugfix
  main/filters.py
  main/views.py
Labels: bugfix

#141 Fixes for improvements list of RW
  main/management/commands/once_update_rw_market_type.py
  main/management/commands/rw_import.py
  main/management/commands/rw_market_import.py
  main/migrations/0045_itemvariation_market_type.py
  main/models.py
  main/templates/main/rw_listings.html
Labels: feature

#145 Fix/active trader
  main/filters.py
  main/management/commands/check_player_stats.py
Labels: bugfix

#146 Navbar Update
  main/templates/main/includes/navbar.html
Labels: feature

#148 Fixes for pagination current page on mobile
  main/templates/main/includes/pagination.html
Labels: bugfix

#149 Fixed item listings cache
  main/views.py
Labels: bugfix

#150 UI improvements for RW before production
  main/management/commands/rw_market_import.py
  main/static/main/css/te.css
  main/templates/main/home.html
  main/templates/main/rw_listings.html
Labels: feature

#160 add pagination to bottom of the pages
  main/static/main/css/te.css
  main/templates/main/all_receipts.html
  main/templates/main/all_sellers.html
  main/templates/main/listings.html
Labels: bugfix

#163 Column selection - price list
  main/templates/main/price_list_creation.html
  main/views.py
Labels: feature

#165 Added ordering to listings API
  main/api.py
Labels: bugfix

#166 hide hidden listings in the api
  main/api.py
Labels: bugfix
