Repository torn-exchange/web, pull requests merged in 2025-02, with the labels that each got.

#99 Add Forum Tutorial
  main/templates/main/home.html
  main/templates/main/includes/navbar.html
  main/templates/main/tutorial.html
  main/urls.py
  main/views.py
Labels: feature

#102 Add votes and forum link to api/profile
  main/api.py
Labels: feature, API

#103 Price List Management page
  main/management/commands/delete_old_keys.py
  main/management/commands/update_items.py
  main/management/commands/update_items_async.py
  main/te_utils.py
  main/templates/main/includes/navbar.html
  main/templates/main/manage_price_list.html
  main/templates/main/price_list_creation.html
  main/urls.py
  main/views.py
  users/migrations/0027_profile_hidden_categories.py
  users/migrations/0028_profile_order_categories.py
  users/models.py
  users/views.py
Labels: bug, feature

#104 links and UI fixes for category management
  main/templates/main/home.html
  main/templates/main/includes/navbar.html
  main/templates/main/includes/profile_card.html
  main/templates/main/manage_price_list.html
  main/views.py
Labels: feature

#105 Dark Theme!
  main/filters.py
  main/static/main/css/custom.css
  main/static/main/css/cyborgcss.css
  main/static/main/css/style.css
  main/templates/main/analytics.html
  main/templates/main/base.html
  main/templates/main/calculator.html
  main/templates/main/edit_services.html
  main/templates/main/employee_listings.html
  main/templates/main/home.html
  main/templates/main/includes/changelog.html
  main/templates/main/includes/dashboard_cards/main_statistics.html
  main/templates/main/includes/dashboard_cards/top_sellers.html
  main/templates/main/includes/footer.html
  main/templates/main/includes/leaderboard.html
  main/templates/main/includes/most_receipts.html
  main/templates/main/includes/navbar.html
  main/templates/main/includes/profile_card.html
  main/templates/main/listings.html
  main/templates/main/losses_listings.html
  main/templates/main/manage_price_list.html
  main/templates/main/price_list.html
  main/templates/main/revives_listings.html
  main/templates/main/search_services.html
  main/templates/main/services_list.html
  main/templates/main/settings.html
  torntrades/settings.py
  users/templates/users/login.html
Labels: feature

#106 Toggle between Dark and Light theme
  README.md
  main/static/main/css/custom.css
  main/templates/main/analytics.html
  main/templates/main/base.html
  main/templates/main/calculator.html
  main/templates/main/home.html
  main/templates/main/includes/navbar.html
  main/templates/main/manage_price_list.html
  main/templates/main/price_list.html
  main/templates/main/price_list_creation.html
  main/templates/main/services_list.html
  main/templates/main/settings.html
  main/views.py
Labels: bug, feature

#95 Update price ep
  main/api.py
  main/swagger.yaml
  main/urls.py
Labels: documentation, feature, API

#108 Introduce Global Fee
  main/filters.py
  main/models.py
  main/templates/main/manage_price_list.html
  main/templates/main/price_list_creation.html
  main/views.py
  torntrades/settings.py
  users/migrations/0029_settings_trade_global_fee.py
  users/models.py
Labels: feature

#110 fix Listing; rename global fee to Item Market Fee
  main/filters.py
  main/templates/main/manage_price_list.html
  main/templates/main/price_list_creation.html
  torntrades/settings.py
Labels: bug

#111 Colors for analytics charts updated
  main/templates/main/analytics.html
Labels: bug
