Repository torn-exchange/web, pull requests merged in 2025-04, with the labels that each got.

#167 ignore global fee for sets
  main/templates/main/price_list_creation.html
Labels: bugfix

#168 new API EP: active_traders
  main/api.py
  main/urls.py
Labels: feature, API

#170 Fixes for Modify Listing API
  main/api.py
  main/swagger.yaml
Labels: bugfix, API

#171 add HTTPS
  main/api.py
  main/views.py
Labels: bugfix

#172 add listings link
  main/templates/main/home.html
  main/templates/main/listings.html
Labels: bugfix

#173 add 3 vault buttons to Calculator page
  main/templates/main/calculator.html
Labels: feature
