Repository torn-exchange/web, pull requests merged in 2025-01, with the labels that each got.

#77 Fix logging issue and cache home page
  main/templates/main/analytics.html
  main/templates/main/base.html
  main/templates/main/price_list.html
  main/views.py
  torntrades/settings.py
Labels: bug

#79 fix error 500s for players that recently renamed
  main/templates/main/price_list.html
  main/views.py
Labels: bug

#80 fix listing sort filter bug
  main/filters.py
  main/templates/main/listings.html
  main/templatetags/custom_tags.py
Labels: bug

#81 Update settings.py
  torntrades/settings.py
Labels: feature

#84 Ability to switch off sets creation
  main/views.py
  users/forms.py
  users/migrations/0026_settings_trade_enable_sets.py
  users/models.py
Labels: feature

#86 TE API
  main/api.py
  main/templates/main/api_home.html
  main/urls.py
Labels: feature, API

#87 Added a couple more endpoints and updated the readme
  README.md
  main/api.py
  main/filters.py
  main/static/main/robots.txt
  main/urls.py
Labels: documentation, feature, API

#88 API: add Receipts and Sellers EP
  main/api.py
  main/templates/main/all_sellers.html
  main/urls.py
  main/views.py
Labels: feature

#90 Introduce links to TornPal market
  main/templates/main/price_list_creation.html
Labels: feature

#91 Added swagger
  main/api.py
  main/static/main/swagger/favicon-16x16.png
  main/static/main/swagger/favicon-32x32.png
  main/static/main/swagger/index.css
  main/static/main/swagger/oauth2-redirect.html
  main/static/main/swagger/swagger-initializer.js
  main/static/main/swagger/swagger-ui-bundle.js
  main/static/main/swagger/swagger-ui-bundle.js.map
  main/static/main/swagger/swagger-ui-es-bundle-core.js
  main/static/main/swagger/swagger-ui-es-bundle-core.js.map
  main/static/main/swagger/swagger-ui-es-bundle.js
  main/static/main/swagger/swagger-ui-es-bundle.js.map
  main/static/main/swagger/swagger-ui-standalone-preset.js
  main/static/main/swagger/swagger-ui-standalone-preset.js.map
  main/static/main/swagger/swagger-ui.css
  main/static/main/swagger/swagger-ui.css.map
  main/static/main/swagger/swagger-ui.js
  main/static/main/swagger/swagger-ui.js.map
  main/swagger.yaml
  main/templates/swagger.html
  main/urls.py
  main/views.py
Labels: documentation, feature, API

#93 Robots.txt fix
  main/urls.py
  main/views.py
Labels: bug

#96 Caching, various optimizations
  main/te_utils.py
  main/templates/main/home.html
  main/templates/main/includes/navbar.html
  main/templates/main/listings.html
  main/views.py
  torntrades/settings.py
Labels: feature

#98 Re-arrange buttons and headings on price list and services list
  main/te_utils.py
  main/templates/main/base.html
  main/templates/main/includes/navbar.html
  main/templates/main/includes/profile_card.html
  main/templates/main/listings.html
  main/templates/main/price_list.html
  main/templates/main/search_services.html
  main/templates/main/services_list.html
  main/views.py
Labels: bug, feature
